### ISSUE TITLE
Code inside alert elements inherit line height from container DIV

### ISSUE THREAD

**Issue by FransBouma** [FransBouma/DocNet#47]
This gives badly formatted code blocks. The fix is:

```css
div.alert > pre > code {
	line-height: initial;
}
```
being added to theme.css
